const fieldTexts = {
	1: {
		content: "Սկսեցի՞նք",
		textcolor: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	2: {
		content: "Ջերմոցային գազերը, որոնցից է նաև ածխաթթու գազը, կլանում են արեգակի էներգիայի մի մասը՝ ջերմոցի պես տաք ու կայուն պահելով Երկիր մոլորակի ջերմաստիճանը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	3: {
		content: "Կլիմայի փոփոխություն",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	4: {
		content: "Նախարդյունաբերական շրջանում (մինչև 1850թ) ածխաթթու գազի քանակը մթնոլորտում կազմել է 280 մաս միլիոնի մեջ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	5: {
		content: "Դու գերադասում ես հեծանիվ վարել, քան ավտոմեքենա։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	6: {
		content: "Կլիման տվյալ տարածքին բնորոշ միջինացված օդերևութաբանական պայմաններն են։ Դա միջին եղանակն է տևական ժամանակի՝ սովորաբար 30 տարվա ընթացքում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	7: {
		content: "1825թ-ին բացվեց առաջին հասարակական երկաթուղին և սկիզբ դրվեց երկաթուղիների դարաշրջանին։ Քարածուխի, փայտի և տորֆի այրումից մեծ քանակությամբ ածխաթթու գազ էր արտանետվում մթնոլորտ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	8: {
		content: "Մարդու գործունեության հետևանքով մթնոլորտ են արտանետվում մեծ քանակությամբ ջերմոցային գազեր, ինչի պատճառով ավելի շատ ջերմություն է թակարդվում ու տաքացնում մեր մոլորակը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	9: {
		content: "Սենյակից դուրս գալիս դու մոռացել ես անջատել լույսը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	10: {
		content: "Նախաարդյունաբերական շրջանի համեմատությամբ արդյունաբերական շրջանում մթնոլորտում մոտ 40%-ով աճեց ածխաթթու գազի քանակությունը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	11: {
		content: "Յուրաքանչյուր տարի դու մեկ ծառ ես տնկում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	12: {
		content: "Ածխաթթու գազի նույն չափաբաժիններով մթնոլորտ շարունակական արտանետումների հետևանքով, մինչև 2100թ մթնոլորտի միջին ջերմաստիճանը կաճի մոտ 2-6  ̊C-ով։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	13: {
		content: "Կլիմայի գլոբալ փոփոխության արդյունքում փոխվում է տեղումների ոչ միայն միջին քանակը, այլ նաև դրանց սեզոնային բաշխումը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	14: {
		content: "Դու երկար ես ցնցուղ ընդունում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	15: {
		content: "Երթևեկությունը հեծանիվով փոխարինելով կրճատվում է ավտոմեքենայի կողմից 1 լիտր բենզինի այրումից  մոտ 2կգ ածխաթթու գազի արտանետումը մթնոլորտ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	16: {
		content: "Հյուսիսային բևեռը 2 ̊C-ով ավելի տաք է, քան 50 տարի առաջ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	17: {
		content: "Դու գերդասում ես օգտագործել վերամշակված թուղթ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	18: {
		content: "Դու դեն ես նետում պլաստիկ շիշը, որի արտադրության համար մթնոլորտ է արտանետվում 1.5կգ ածխաթթու գազ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	19: {
		content: "Անտառհատումների հետևանքով մթնոլորտ է արտանետվում ոչ միայն ծառերի բնափայտի մեջ կուտակված ածխածինը, այլև կրճատվում է ծառերի կողմից ածխաթթու գազը կլանելու հնարավորությունը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	20: {
		content: "Եթե 10 տարվա ընթացքում յուրաքանչյուրս 2-ական ծառ տնկենք, դա կփոխհատուցվի վերջին 10 տարիների ընթացքում հատված ծառերի ընդհանուր քանակը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	21: {
		content: "Շվեդիայում կա գնացք, որն աշխատում է թափոնների քայքայումից առաջացող մեթանով՝ դրանով կրճատելով ջերմոցային գազերի արտանետումները։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	22: {
		content: "Մեկ տոննա վերամշակված թուղթը խնայում է 17 ծառ, 320 լիտր նավթ, 4100 կիլովատ էներգիա, 3.2 խորանարդ մետր տարածք և 30 կգ օդի աղտոտում:",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	23: {
		content: "Դու սիրում ես անտառներում խարույկ վառել։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	24: {
		content: "Ավտոմեքենայով յուրաքանչյուր 10կմ ճանապարհորդելիս մթնոլորտ է արտանետվում 3.7-18.3կգ ածխաթթու գազ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	25: {
		content: "5000 տարի առաջ Հայաստանի 35%-ը անտառապատ էր, իսկ ներկայում անտառները զբաղեցնում են 10%-ից պակաս տարածք։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	26: {
		content: "1990-ական թվականները վերջին հազարամյակի ամենատաք տասնամյակն էր։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	27: {
		content: "Դուք տեղադրել եք արևային վահանակներ Ձեր տան կտուրին։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	28: {
		content: "Դու սիրում ես ավտոմեքենայով շատ շրջագայել։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	29: {
		content: "«Ածխածնի հետքը» ջերմոցային գազերի այն քանակն է, որը կուտակում է յուրաքանչյուր ոք ամենօրյա գործունեության ընթացքում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	30: {
		content: "Երկրաջերմային էներգիայի արտադրությունը զարգացման դեպքում 1000 անգամ ավելի շատ էլեկտրաէներգիա կարող է մատակարարել, քան ողջ աշխարհում դրա սպառումն է։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	31: {
		content: "Հիմալայան սառցադաշտերի անհետացման դեպքում 2.6 միլիարդ մարդ խմելու ջրի պակաս կունենա։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	32: {
		content: "Արևային վահանակները կլանում են արևի լույսը՝ այն փոխարկելով էլեկտրաէներգիայի։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	33: {
		content: "Էլեկտրոմոբիլները աշխատում են էլեկտրականությամբ, այլ ոչ բենզինով և չեն աղտոտում օդը։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	34: {
		content: "Հողագործության արդյունքում հողում կուտակված ածխաթթու գազը դուրս է գալիս մթնոլորտ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	35: {
		content: "Բրինձի պլանտացիաներից մթնոլորտ է արտանետվում մեթան (ևս մեկ ջերմոցային գազ)։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	36: {
		content: "Գոմաղբից ու ընտանի կենդանիների օրգանիզմում բուսական սննդի մարսումից մթնոլորտ է արտանետվում մեթան։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	37: {
		content: "Մեթանը միևնույն քանակի ածխաթթու գազի համեմատությամբ 25 անգամ ավելի է նպաստում ջերմոցային էֆեկտին։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	38: {
		content: "Դու կոմպոստացնում ես սննդի մնացորդները։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	39: {
		content: "Պարարտանյութերի օգտագործումը բերում է ազոտի ենթօքսիդի (ևս մեկ ջերմոցային գազի) արտանետման։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	40: {
		content: "Դու հաճախակի ես միս ուտում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	41: {
		content: "Ազոտի ենթօքսիդի կյանքի տևողությունը մթնոլորտում 114 տարի է։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	42: {
		content: "Կենսազանգվածի (մահացած բույսերից, խոտից, տերևներից, սննդի մնացորդների քայքայումից ստացվող օրգանակն նյութեր) էներգիան կարելի է օգտագործել կենսագազ արտադրելու և ծառերը պարարտացնելու համար։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	43: {
		content: "Օրգանական ֆերմաներն ավելի քիչ հանածո վառելիք են սպառում և չեն օգտագործում արհեստական պարարտանյութեր։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	44: {
		content: "Դուք տանը լուսադիոդային (LED) լամպեր եք օգտագործում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "green",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	45: {
		content: "Լավ ջերմամեկուսացված շենքերը էլեկտրաարդյունավետ են, քանի որ ավելի շատ տաքություն են պահպանում։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	46: {
		content: "Դու քո այգին պարարտացնում ես քիմիական նյութերով։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "red",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	47: {
		content: "26Վտ-ոց LED լամպը փոխարինում է 100Վտ-ոց շիկացման լամպին՝ ծառայելով 6 -12 անգամ ավելի երկար։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	48: {
		content: "Իրազեկվածությունը կօգնի զարգացնել գաղափարներ և գտնել լուծումներ կլիմայի փոփոխության գլոբալ հիմնահարցի շուրջ։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	49: {
		content: "Դու հասար Կլիմայի պահպանության։",
		color: "black",
		borderColor: "1px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
		fieldImg: "",
		fieldColor: "",
	},
	101:{
		head: "կանոններ",
		content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo odit labore corrupti distinctio quod officiis, animi fuga asperiores minus nesciunt voluptatem fugit nihil quo repellendus sed deleniti, illum delectus nisi. Quisquam vitae nisi saepe nihil autem, sit mollitia accusantium dicta numquam fugiat error. Non recusandae accusantium, excepturi exercitationem esse sunt.",
		color: "black",
		borderColor: "3px solid black",
		bgColor: "antiquewhite",
		popupImg: "",
	}
};